GET https://localhost:5001/Employees

###
GET https://localhost:5001/Employees/Brian%20Kernighan

###
POST https://localhost:5001/Employees
Content-Type: application/json

{
    "name": "Troy Hunt",
    "occupation": "Tester"
}

###
POST https://localhost:5001/Employees
Content-Type: application/x-www-form-urlencoded

name=Troy%20Hunt&occupation=Tester

###
PUT https://localhost:5001/Employees
Content-Type: application/json

{
    "name": "Brian Kernighan",
    "occupation": "Tester"
}

###
PUT https://localhost:5001/Employees
Content-Type: application/json

{
    "name": "Troy Hunt",
    "occupation": "Tester"
}

###
DELETE https://localhost:5001/Employees/Brian%20Kernighan